server:
  port: 8089
  servlet:
    context-path: /client
spring:
  application:
    name: service-client
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: user
    password: 123